doc-warnings: false
test-warnings: false
strictness: medium
max-line-length: 80
autodetect: true
requirements:
    - requirements.txt
ignore-paths:
    - docs
    - examples
    - tempo2Test
    - validation
    - pint/scripts
    - pint/extern
    - pint/profiling
pylint:
  disable:
    - logging-format-interpolation
python-targets:
    - 2
    - 3
