coverage:
    status:
        project:
            default:
                informational: true
                target: auto
                # this allows a drop from the previous base commit coverage
                threshold: 1%
        patch:
            default:
                informational: true
